AdobeDocs/cloudmanager-api-docs

swagger-specs/api.yaml

Updated Swagger API docs for 2020.12 release

Cloud Manager 2020.12 API Docs

---

receiving-events.md

`buildImage` was missing from list of actions.

Add missing event action

---

.eslintrc
gatsby-config.js
package.json
src/components/playground/common-proptypes.js
src/components/playground/constants.js
src/components/playground/custom-request-dialog.js
src/components/playground/disabled.js
src/components/playground/index.js
src/components/playground/link-table.js
src/components/playground/org-id-selector.js
src/components/playground/playground-header.js
src/components/playground/request-pane.js
src/pages/reference/playground.md
yarn.lock

Add a new API Playground that enables logged in user to make API calls from the docs site.
#69

Add an API Playground

---

package.json
src/components/playground/link-table.js
src/components/playground/template-request-dialog.js
yarn.lock

Add a template link dialog with the variables required by the HAL link.
#79
Manual testing

fix(playground): add template link dialog. fixes #79

---

package.json
src/components/playground/request-pane.js
yarn.lock

Update playground to use history library to manage back/forward button.
#92 
Meets expected behavior of back/forward button.
Manual testing

fix(playground): making it so the back button work. fixes #92

---

gatsby-config.js
src/pages/guides/api-usage/adding-custom-domain-names.md
src/pages/guides/api-usage/index.md

Adding custom domain names
How to add custom domain names
Dunno. I was told to do this. See CQDOC-18774
I am really motivated to do what I am told.
Make changes. Tested locally with yarn as described in the README.md.
Too hot for TV

Adding custom domain names

---

.gitignore
swagger-specs/api.yaml

- pagination query params used to list all pipelines from a specific program
- stepId query param used to re-execute a specific pipeline execution

Cloud Manager 2022.4.0 API Docs

---

src/data/permissions.json
swagger-specs/api.yaml

Add documentation for the new delete network infrastructure API

Cloud Manager 2022.5.0 API Docs

---

src/pages/index.md

Fixing link

---

src/data/permissions.json
swagger-specs/api.yaml

Cloud Manager 2022.6.0 API Docs

Cloud Manager 2022.6.0 API Docs

---

swagger-specs/api.yaml

Updated getPrograms description in yaml to indicate that it is deprecated. CQDOC-19457

Deprecate getPrograms, link to getProgramsForTenant

---

swagger-specs/api.yaml

Correction to typo in the description of the Lists Programs API (CQDOC-19457) introduced in PR #220.

Correction of typo introduced in PR#220

---

src/data/permissions.json
swagger-specs/api.yaml

Adding public documentation for Go Live feature
[CMGR-28264](https://jira.corp.adobe.com/browse/CMGR-28264)

goLive public API changes

---

swagger-specs/api.yaml

Cloud Manager 2022.11.0 API Docs

---

swagger-specs/api.yaml

[CMGR-41919] public api docs for advanced networking

---

src/data/permissions.json
src/pages/guides/api-usage/creating-programs-and-environments.md
src/pages/reference/models.md
swagger-specs/api.yaml

[CMGR-40469] : public doc for additional publish region

---

README.md

Add trivial change to create PR and verify all workflows.

Extra space

---

.github/workflows/ci.yml
src/data/permissions.json
swagger-specs/api.yaml

ContentSet and ContentFlow public APIs
Public API specs for:
- Content Set APIs 
- Content Flow APIs
APIs are now available via cloudmanager.adobe.io
Customers have been asking about public API availability
Changeges have been tested using 'yarn dev'

CMGR-39968 API Public documentation readiness for Content Flow

---

swagger-specs/api.yaml

Documentation change
See PR #270 and CQDOC-20835

CQDOC-20835

---

src/data/permissions.json
swagger-specs/api.yaml

- [x ] New feature (non-breaking change which adds functionality)
- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

CMGR-49416: adds public docs for content flow logs download

---

swagger-specs/api.yaml

Added swagger data from self-service-config-build and cm-eds sites microservices in the context of Cloud Manager.
Added swagger data from self-service-config-build and cm-eds sites microservices in the context of Cloud Manager.
https://git.corp.adobe.com/experience-platform/cloudmanager-api-docs-tools/pull/14
[CMGR-62168](https://jira.corp.adobe.com/browse/CMGR-62168)
Adding swagger data from other critical microservices from the Cloud Manager environment

[CMGR-62168] Updates to API documentation to include DV certs, EDS
